### ISSUE TITLE
What to do with this repo?

### ISSUE THREAD

**Issue by jrmlhermitte** [jrmlhermitte/bluesky-zmq#1]
Currently bluesky-zmq is deployed via ansible playbooks.
We could consider making a Debian package that has this installed under systemd.

## Alternatives
Add the systemd service using purely ansible but the Debian package may be cleaner)

Should decide whether to keep this and use Debian packaging or just use ansible.
This could also be used as a model for how to create minimal Debian packages.

**Comment by mrakitin** [comment]
Hi @jrmlhermitte, nice to see you here 🙂. Thanks for going through the issues/PRs. We don't use Debian anymore, probably worth archiving this repo. @stuartcampbell, thoughts?
